site_name: Wraith's Notebook
dev_addr: '127.0.0.1:5500' #默认值
theme:
  name: 'material'
  custom_dir: docs/overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: grey
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: white
      toggle:
        icon: material/weather-night 
        name: Switch to light mode
  language: 'zh'
  font: false
#    text: LXGW WenKai GB Screen 
#    code: JetBrains Mono Regular, LXGW WenKai GB Screen
  logo: assets/images/clipboard.svg # logo.jpg
  favicon: assets/images/clipboard2.svg
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
extra_css:
  - stylesheets/extra.css
  - https://cdn.tonycrane.cc/utils/katex.min.css
  - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  - https://cdn.tonycrane.cc/lxgw/lxgwscreen.css
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      #fallback_to_build_date: true
      enable_creation_date: true
extra_javascript:
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
nav:
  - Home: index.md
  - Course: 
    - course/index.md
    - Mathematical Basic:
      - Discrete Mathemtics: course/MathematicalBasic/DiscreteMathemtics.md
      - Calculus: course/MathematicalBasic/Calculus.md
      - College Physics: course/MathematicalBasic/CollegePhysics/电磁学.md
    - Program:
      - Python: 
        - course/python/index.md
        - Python入门: course/python/python1.md
        - 数据类型: course/python/python2.md
        - 条件语句: course/python/python3.md
        - 循环语句: course/python/python4.md
        - 函数: course/python/python5.md
      - BasicDataStructure:
        - course/Program/BasicDataStructure/index.md
        - 算法分析: course/Program/BasicDataStructure/AlgorithmAnalysis.md
        - 抽象数据结构: course/Program/BasicDataStructure/List.md
        - 树: course/Program/BasicDataStructure/Tree.md
        - 堆: course/Program/BasicDataStructure/Heap.md
        - 并查集: course/Program/BasicDataStructure/DisjointSet.md
      - Cpp: 
        - course/Program/cpp/index.md
        - book: course/Program/cpp/1.md
      - Object-oriented Programming: 
        - course/Program/Oop/index.md
    - ComputerSystem:
      - System1:
        - 单周期CPU复习: course/ComputerSystem/ComputerSystem1/preview.md
      - System2: 
        - course/ComputerSystem/ComputerSystem2/index.md
        - 指令集系统: course/ComputerSystem/ComputerSystem2/InstructionSet.md
        - 流水线: course/ComputerSystem/ComputerSystem2/pipeline.md
        - 流水线复习: course/ComputerSystem/ComputerSystem2/pipelinesum.md
        - lab4: course/ComputerSystem/ComputerSystem2/lab4.md
      - ComputerOrganization:
        - 计算机抽象及相关技术: course/ComputerOrganization/ComputerOrganization1.md
    - Economics: 
      - AgriculturalEconomics: 
        - course/Economics/AgriculturalEconomics/index.md
      - InternationalTrade: 
        - course/Economics/InternationalTrade/index.md
      - WesternEconomics: 
        - course/Economics/WesternEconomics/index.md
        - 微经-需求、供给和均衡价格: course/Economics/WesternEconomics/microeconomics1.md
    - Policy:
      - course/Policy/index.md
      - 政策科学的发展历程: course/Policy/1.md
      - 影响公共政策制定的因素: course/Policy/3.md
      - 公共政策的制定过程: course/Policy/4.md
    - IdeologyAndPoitics:
      - Military:
        - course/IdeologyAndPoitics/military1.md
  - Book Notes:
    - 社会认知论:
      - read/社会认知论/index.md
  - Tool:
    - tool/index.md
    - Mkdocs: tool/MkDocs.md
    - Photograph: tool/photography.md
#   - C Code Display: c.md
  - Collection:
    - collection/index.md
    - 2022 sentence: collection/sentence.md
    - 2022 paragraph: collection/paragraph.md
    - 2023 sentence: collection/sentence2023.md
    - 2023 paragraph: collection/paragraph2023.md
    - CCTV collection: collection/cctv.md
    - verse: collection/verse.md
    - poem: collection/poem.md
    - elegance: collection/elegance.md
  - Life:
    - life/index.md
    - Music: life/music.md
    - plan: life/plan.md
  - Task:
    - task/index.md
    - 2023.11.29: task/plan.md
